# Site basics
locale: en
url: "https://jessezhou-1.github.io"
baseurl: "/gsc-website"
repository: "JesseZhou-1/gsc-website"
title: "Society for Social Research (Graduate Student Council)"
masthead_title: "Society for Social Research"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache

# Pages and posts
include:
  - _pages
defaults:
  - scope: { path: "" }
    values:
      layout: single
      comments: false
  - scope: { path: "_posts" }
    values:
      layout: single
      comments: false
