name: Label funding amount
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply amount tier labels
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const match = body.match(/Amount requested \(USD, numbers only\)\n\n([0-9]+)/);
            if (!match) return;
            const amount = parseInt(match[1], 10);
            let tier;
            if (amount < 500) tier = 'lt-500';
            else if (amount < 1000) tier = '500-999';
            else tier = 'gte-1000';
            const labels = new Set(context.payload.issue.labels.map(l => l.name));
            ['lt-500','500-999','gte-1000'].forEach(l => labels.delete(l));
            labels.add(tier);
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: Array.from(labels)
            });
